import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ToastProvider from "@/context/ToastProvider";
import Navbar from "@/component/nav-bar/Navbar";
import { Container } from "@mui/material";
import SessionProvider from "@/context/SessionProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "E-Commerce-Store",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider>
          <Navbar />
          <ToastProvider>
            <Container fixed>{children}</Container>
          </ToastProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
